/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.0-beta).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.pixolution.embeddingsGrid.api;

import de.pixolution.embeddingsGrid.model.PingResponseJson;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "ping", description = "the ping API")
public interface PingApi {

    default PingApiDelegate getDelegate() {
        return new PingApiDelegate() {};
    }

    /**
     * GET /ping
     *
     * @return Ping back (status code 200)
     */
    @Operation(
        operationId = "pingGet",
        responses = {
            @ApiResponse(responseCode = "200", description = "Ping back", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PingResponseJson.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/ping",
        produces = { "application/json" }
    )
    default ResponseEntity<PingResponseJson> pingGet(
        
    ) {
        return getDelegate().pingGet();
    }

}
